use crate::models::demo_shared::DemoHooks;

// * This file was generated automatically with build_registry.

pub const SIDENAV_HOOKS_BROWSER: &[DemoHooks] = &[
    DemoHooks {
        name: "Use User Media",
        path_url: "use-user-media",
        path_mdx: "content-mdx/hooks/browser/use-user-media.mdx",
        description: "Rust hook that provides a way to get the user's media devices.",
        tags: &["hooks"],
    },
    DemoHooks {
        name: "Use Locale",
        path_url: "use-locale",
        path_mdx: "content-mdx/hooks/browser/use-locale.mdx",
        description: "Rust hook that provides a way to format dates, numbers, and strings using the Internationalization API.",
        tags: &["hooks"],
    },
    DemoHooks {
        name: "Use Locales",
        path_url: "use-locales",
        path_mdx: "content-mdx/hooks/browser/use-locales.mdx",
        description: "Rust hook that provides a way to format dates, numbers, and strings using the Internationalization API.",
        tags: &["hooks"],
    },
    DemoHooks {
        name: "Use Broadcast Channel",
        path_url: "use-broadcast-channel",
        path_mdx: "content-mdx/hooks/browser/use-broadcast-channel.mdx",
        description: "Rust hook that provides a BroadcastChannel instance.",
        tags: &["hooks"],
    },
    DemoHooks {
        name: "Use Web Notification",
        path_url: "use-web-notification",
        path_mdx: "content-mdx/hooks/browser/use-web-notification.mdx",
        description: "Rust hook that provides a way to display a notification to the user.",
        tags: &["hooks"],
    },
    DemoHooks {
        name: "Use Display Media",
        path_url: "use-display-media",
        path_mdx: "content-mdx/hooks/browser/use-display-media.mdx",
        description: "Rust hook that provides a way to display media.",
        tags: &["hooks"],
    },
    DemoHooks {
        name: "Use Prefers Reduced Motion",
        path_url: "use-prefers-reduced-motion",
        path_mdx: "content-mdx/hooks/browser/use-prefers-reduced-motion.mdx",
        description: "Rust hook that provides a way to check if the user has enabled reduced motion.",
        tags: &["hooks"],
    },
    DemoHooks {
        name: "Use Css Var",
        path_url: "use-css-var",
        path_mdx: "content-mdx/hooks/browser/use-css-var.mdx",
        description: "Rust hook that provides a way to read and write CSS variables.",
        tags: &["hooks"],
    },
    DemoHooks {
        name: "Use Media Query",
        path_url: "use-media-query",
        path_mdx: "content-mdx/hooks/browser/use-media-query.mdx",
        description: "Rust hook that provides a way to check if a media query matches the current browser environment.",
        tags: &["hooks"],
    },
    DemoHooks {
        name: "Use Intl Number Format",
        path_url: "use-intl-number-format",
        path_mdx: "content-mdx/hooks/browser/use-intl-number-format.mdx",
        description: "Rust hook that provides a way to format numbers using the Internationalization API.",
        tags: &["hooks"],
    },
    DemoHooks {
        name: "Use Color Mode",
        path_url: "use-color-mode",
        path_mdx: "content-mdx/hooks/browser/use-color-mode.mdx",
        description: "Rust hook that provides the current color mode of the browser.",
        tags: &["hooks"],
    },
    DemoHooks {
        name: "Use Cookie",
        path_url: "use-cookie",
        path_mdx: "content-mdx/hooks/browser/use-cookie.mdx",
        description: "Rust hook that provides a way to read and write cookies.",
        tags: &["hooks"],
    },
    DemoHooks {
        name: "Use Clipboard",
        path_url: "use-clipboard",
        path_mdx: "content-mdx/hooks/browser/use-clipboard.mdx",
        description: "Rust hook that provides a way to read from and write to the system clipboard.",
        tags: &["hooks"],
    },
    DemoHooks {
        name: "Use Permission",
        path_url: "use-permission",
        path_mdx: "content-mdx/hooks/browser/use-permission.mdx",
        description: "Rust hook that provides a way to check if a feature is available in the user's browser.",
        tags: &["hooks"],
    },
    DemoHooks {
        name: "Use Breakpoints",
        path_url: "use-breakpoints",
        path_mdx: "content-mdx/hooks/browser/use-breakpoints.mdx",
        description: "Rust hook that provides the current breakpoint of the browser.",
        tags: &["hooks"],
    },
    DemoHooks {
        name: "Use Storage",
        path_url: "use-storage",
        path_mdx: "content-mdx/hooks/browser/use-storage.mdx",
        description: "Rust hook that provides a way to read and write to the browser's storage.",
        tags: &["hooks"],
    },
    DemoHooks {
        name: "Use Event Listener",
        path_url: "use-event-listener",
        path_mdx: "content-mdx/hooks/browser/use-event-listener.mdx",
        description: "Rust hook that provides a way to listen for events.",
        tags: &["hooks"],
    },
];