use crate::models::demo_shared::DemoCore;

// * This file was generated automatically with build_registry.

pub const SIDENAV_CORE_CORE: &[DemoCore] = &[
    DemoCore {
        name: "Sheet",
        path_url: "sheet",
        path_mdx: "content-mdx/core/core/sheet.mdx",
        description: "Rust UI component that displays a sheet.",
        tags: &["navigation"],
    },
    DemoCore {
        name: "Alert",
        path_url: "alert",
        path_mdx: "content-mdx/core/core/alert.mdx",
        description: "Rust UI component that displays a callout to the user.",
        tags: &[],
    },
    DemoCore {
        name: "Tooltip",
        path_url: "tooltip",
        path_mdx: "content-mdx/core/core/tooltip.mdx",
        description: "Rust UI component that displays an information related to an element when the element receives keyboard focus or the mouse hovers over it.",
        tags: &["utils"],
    },
    DemoCore {
        name: "Animate Group",
        path_url: "animate-group",
        path_mdx: "content-mdx/core/core/animate-group.mdx",
        description: "A wrapper for animations, made with Tailwind CSS. Works seamlessly with any children component.",
        tags: &["animation"],
    },
    DemoCore {
        name: "Label",
        path_url: "label",
        path_mdx: "content-mdx/core/core/label.mdx",
        description: "Rust UI component that displays a label for an input field.",
        tags: &[],
    },
    DemoCore {
        name: "Navigation Menu",
        path_url: "navigation-menu",
        path_mdx: "content-mdx/core/core/navigation-menu.mdx",
        description: "Rust UI component that displays a navigation menu.",
        tags: &["navigation"],
    },
    DemoCore {
        name: "Alert Dialog",
        path_url: "alert-dialog",
        path_mdx: "content-mdx/core/core/alert-dialog.mdx",
        description: "Rust UI component that displays a modal dialog that interrupts the user with important content and expects a response.",
        tags: &["dialog"],
    },
    DemoCore {
        name: "Text Area",
        path_url: "text-area",
        path_mdx: "content-mdx/core/core/text-area.mdx",
        description: "Rust UI component that displays a text area.",
        tags: &["input"],
    },
    DemoCore {
        name: "Animate",
        path_url: "animate",
        path_mdx: "content-mdx/core/core/animate.mdx",
        description: "A wrapper for animations, made with Tailwind CSS. Works seamlessly with any children component.",
        tags: &["animation"],
    },
    DemoCore {
        name: "Popover",
        path_url: "popover",
        path_mdx: "content-mdx/core/core/popover.mdx",
        description: "Rust UI component that displays rich content in a portal, triggered by a button.",
        tags: &["popover"],
    },
    DemoCore {
        name: "Card",
        path_url: "card",
        path_mdx: "content-mdx/core/core/card.mdx",
        description: "Rust UI component that displays a card with header, content and footer.",
        tags: &["card"],
    },
    DemoCore {
        name: "Button",
        path_url: "button",
        path_mdx: "content-mdx/core/core/button.mdx",
        description: "Rust UI component that displays a button or a component that looks like a button.",
        tags: &["button"],
    },
    DemoCore {
        name: "Toast",
        path_url: "toast",
        path_mdx: "content-mdx/core/core/toast.mdx",
        description: "Rust UI component that displays a toast notification.",
        tags: &["toast"],
    },
    DemoCore {
        name: "Badge",
        path_url: "badge",
        path_mdx: "content-mdx/core/core/badge.mdx",
        description: "Rust UI component that displays a badge or a component that looks like a badge.",
        tags: &[],
    },
    DemoCore {
        name: "Separator",
        path_url: "separator",
        path_mdx: "content-mdx/core/core/separator.mdx",
        description: "Rust UI component that displays a separator line.",
        tags: &[],
    },
    DemoCore {
        name: "Table",
        path_url: "table",
        path_mdx: "content-mdx/core/core/table.mdx",
        description: "Rust UI component that displays a table with header, body and footer.",
        tags: &["table"],
    },
    DemoCore {
        name: "Skeleton",
        path_url: "skeleton",
        path_mdx: "content-mdx/core/core/skeleton.mdx",
        description: "Rust UI component that show a placeholder while content is loading.",
        tags: &[],
    },
    DemoCore {
        name: "Input",
        path_url: "input",
        path_mdx: "content-mdx/core/core/input.mdx",
        description: "Rust UI component that displays an input field that allows the user to enter text.",
        tags: &["input"],
    },
    DemoCore {
        name: "Select",
        path_url: "select",
        path_mdx: "content-mdx/core/core/select.mdx",
        description: "Rust UI component that displays a dropdown menu that allows the user to select an option.",
        tags: &["select"],
    },
    DemoCore {
        name: "Headings",
        path_url: "headings",
        path_mdx: "content-mdx/core/core/headings.mdx",
        description: "Rust UI component that displays a heading with premade styles and animations.",
        tags: &["headings"],
    },
    DemoCore {
        name: "Dropdown Menu",
        path_url: "dropdown-menu",
        path_mdx: "content-mdx/core/core/dropdown-menu.mdx",
        description: "Rust UI component that displays a dropdown menu.",
        tags: &["dropdown"],
    },
    DemoCore {
        name: "Command",
        path_url: "command",
        path_mdx: "content-mdx/core/core/command.mdx",
        description: "Fast, composable, unstyled command menu for Leptos.",
        tags: &[],
    },
    DemoCore {
        name: "Dropdown",
        path_url: "dropdown",
        path_mdx: "content-mdx/core/core/dropdown.mdx",
        description: "Rust UI component that displays a menu to the user — such as a set of actions or functions — triggered by a button.",
        tags: &["dropdown"],
    },
    DemoCore {
        name: "Breadcrumb",
        path_url: "breadcrumb",
        path_mdx: "content-mdx/core/core/breadcrumb.mdx",
        description: "Rust UI component that displays the path to the current resource using a hierarchy of links.",
        tags: &["navigation"],
    },
    DemoCore {
        name: "Dialog",
        path_url: "dialog",
        path_mdx: "content-mdx/core/core/dialog.mdx",
        description: "Rust UI component that displays a modal dialog that the user can interact with.",
        tags: &["dialog"],
    },
    DemoCore {
        name: "Multi Select",
        path_url: "multi-select",
        path_mdx: "content-mdx/core/core/multi-select.mdx",
        description: "Rust UI component that displays a multi select input field.",
        tags: &[],
    },
];