use crate::models::demo_shared::DemoHooks;

// * This file was generated automatically with build_registry.

pub const SIDENAV_HOOKS_REACTIVITY: &[DemoHooks] = &[
    DemoHooks {
        name: "Use RAF Fn",
        path_url: "use-raf-fn",
        path_mdx: "content-mdx/hooks/reactivity/use-raf-fn.mdx",
        description: "Rust hook that provides a way to execute a function at a regular interval.",
        tags: &["hooks"],
    },
    DemoHooks {
        name: "Use Interval",
        path_url: "use-interval",
        path_mdx: "content-mdx/hooks/reactivity/use-interval.mdx",
        description: "Rust hook that provides a way to execute a function at a regular interval.",
        tags: &["hooks"],
    },
    DemoHooks {
        name: "Use Watch Throttled",
        path_url: "use-watch-throttled",
        path_mdx: "content-mdx/hooks/reactivity/use-watch-throttled.mdx",
        description: "Rust hook that provides a way to watch a value and throttle it.",
        tags: &["hooks"],
    },
    DemoHooks {
        name: "Use Debounce",
        path_url: "use-debounce",
        path_mdx: "content-mdx/hooks/reactivity/use-debounce.mdx",
        description: "Rust hook that provides a way to debounce a value.",
        tags: &["hooks"],
    },
    DemoHooks {
        name: "Use Watch Debounced",
        path_url: "use-watch-debounced",
        path_mdx: "content-mdx/hooks/reactivity/use-watch-debounced.mdx",
        description: "Rust hook that provides a way to watch a value and debounce it.",
        tags: &["hooks"],
    },
    DemoHooks {
        name: "Use Sync Signal",
        path_url: "use-sync-signal",
        path_mdx: "content-mdx/hooks/reactivity/use-sync-signal.mdx",
        description: "Rust hook that provides a way to sync a signal with a value.",
        tags: &["hooks"],
    },
    DemoHooks {
        name: "Use Throttle Fn",
        path_url: "use-throttle-fn",
        path_mdx: "content-mdx/hooks/reactivity/use-throttle-fn.mdx",
        description: "Rust hook that provides a way to throttle a function.",
        tags: &["hooks"],
    },
    DemoHooks {
        name: "Use Interval Fn",
        path_url: "use-interval-fn",
        path_mdx: "content-mdx/hooks/reactivity/use-interval-fn.mdx",
        description: "Rust hook that provides a way to execute a function at a regular interval.",
        tags: &["hooks"],
    },
    DemoHooks {
        name: "Use Throttle",
        path_url: "use-throttle",
        path_mdx: "content-mdx/hooks/reactivity/use-throttle.mdx",
        description: "Rust hook that provides a way to throttle a value.",
        tags: &["hooks"],
    },
    DemoHooks {
        name: "Use Timestamp",
        path_url: "use-timestamp",
        path_mdx: "content-mdx/hooks/reactivity/use-timestamp.mdx",
        description: "Rust hook that provides a way to get the current timestamp.",
        tags: &["hooks"],
    },
    DemoHooks {
        name: "Use Infinite Scroll",
        path_url: "use-infinite-scroll",
        path_mdx: "content-mdx/hooks/reactivity/use-infinite-scroll.mdx",
        description: "Rust hook that provides a way to implement infinite scrolling.",
        tags: &["hooks"],
    },
    DemoHooks {
        name: "Use Key Press",
        path_url: "use-key-press",
        path_mdx: "content-mdx/hooks/reactivity/use-key-press.mdx",
        description: "Rust hook that provides a way to detect key presses.",
        tags: &["hooks"],
    },
    DemoHooks {
        name: "Use Debounce Fn",
        path_url: "use-debounce-fn",
        path_mdx: "content-mdx/hooks/reactivity/use-debounce-fn.mdx",
        description: "Rust hook that provides a way to debounce a function.",
        tags: &["hooks"],
    },
    DemoHooks {
        name: "Use Timeout Fn",
        path_url: "use-timeout-fn",
        path_mdx: "content-mdx/hooks/reactivity/use-timeout-fn.mdx",
        description: "Rust hook that provides a way to execute a function after a delay.",
        tags: &["hooks"],
    },
    DemoHooks {
        name: "Use Watch Pausable",
        path_url: "use-watch-pausable",
        path_mdx: "content-mdx/hooks/reactivity/use-watch-pausable.mdx",
        description: "Rust hook that provides a way to watch a value and pause it.",
        tags: &["hooks"],
    },
];