use crate::models::demo_shared::DemoExtensions;

// * This file was generated automatically with build_registry.

pub const SIDENAV_EXTENSIONS_OTHERS: &[DemoExtensions] = &[
    DemoExtensions {
        name: "Hamburger Menus",
        path_url: "hamburger-menus",
        path_mdx: "content-mdx/extensions/others/hamburger-menus.mdx",
        description: "Rust UI component that displays a collection of hamburger menus.",
        tags: &[],
    },
    DemoExtensions {
        name: "Cards Slider",
        path_url: "cards-slider",
        path_mdx: "content-mdx/extensions/others/cards-slider.mdx",
        description: "Rust UI component that displays a CSS only cards slider.",
        tags: &[],
    },
    DemoExtensions {
        name: "Floating Button Menu",
        path_url: "floating-button-menu",
        path_mdx: "content-mdx/extensions/others/floating-button-menu.mdx",
        description: "Rust UI component that displays a floating button menu.",
        tags: &[],
    },
    DemoExtensions {
        name: "Meteor Effect",
        path_url: "meteor-effect",
        path_mdx: "content-mdx/extensions/others/meteor-effect.mdx",
        description: "A meteor effect, made with Tailwind CSS.",
        tags: &[],
    },
    DemoExtensions {
        name: "Blurry Blob",
        path_url: "blurry-blob",
        path_mdx: "content-mdx/extensions/others/blurry-blob.mdx",
        description: "Rust UI component that displays a blurry blob.",
        tags: &[],
    },
    DemoExtensions {
        name: "Card 3D Hover",
        path_url: "card-3d-hover",
        path_mdx: "content-mdx/extensions/others/card-3d-hover.mdx",
        description: "Rust UI component that displays a card 3D hover.",
        tags: &[],
    },
    DemoExtensions {
        name: "Radar",
        path_url: "radar",
        path_mdx: "content-mdx/extensions/others/radar.mdx",
        description: "Rust UI component that displays a radar.",
        tags: &[],
    },
    DemoExtensions {
        name: "Card Tilting",
        path_url: "card-tilting",
        path_mdx: "content-mdx/extensions/others/card-tilting.mdx",
        description: "Rust UI component that displays a card tilting.",
        tags: &[],
    },
    DemoExtensions {
        name: "CTA Animation On Hover",
        path_url: "cta-animation-on-hover",
        path_mdx: "content-mdx/extensions/others/cta-animation-on-hover.mdx",
        description: "Rust UI component that displays a CSS CTA animation on hover.",
        tags: &[],
    },
    DemoExtensions {
        name: "Masonry",
        path_url: "masonry",
        path_mdx: "content-mdx/extensions/others/masonry.mdx",
        description: "Rust UI component that displays a masonry layout.",
        tags: &[],
    },
    DemoExtensions {
        name: "Slider Hover",
        path_url: "slidee-hover",
        path_mdx: "content-mdx/extensions/others/slidee-hover.mdx",
        description: "Rust UI component that displays a slider hover effect.",
        tags: &[],
    },
    DemoExtensions {
        name: "Docker",
        path_url: "docker",
        path_mdx: "content-mdx/extensions/others/docker.mdx",
        description: "Rust UI component that displays a docker.",
        tags: &[],
    },
    DemoExtensions {
        name: "Dropzone",
        path_url: "dropzone",
        path_mdx: "content-mdx/extensions/others/dropzone.mdx",
        description: "Rust UI component that displays a dropzone.",
        tags: &[],
    },
    DemoExtensions {
        name: "Blockquote",
        path_url: "blockquote",
        path_mdx: "content-mdx/extensions/others/blockquote.mdx",
        description: "Rust UI component that displays a blockquote.",
        tags: &[],
    },
    DemoExtensions {
        name: "Cards Direction Aware",
        path_url: "cards-direction-aware",
        path_mdx: "content-mdx/extensions/others/cards-direction-aware.mdx",
        description: "Rust UI component that displays a cards direction aware.",
        tags: &[],
    },
    DemoExtensions {
        name: "Cards Repushing",
        path_url: "cards-repushing",
        path_mdx: "content-mdx/extensions/others/cards-repushing.mdx",
        description: "Rust UI component that displays a cards repushing.",
        tags: &[],
    },
    DemoExtensions {
        name: "Spotlight",
        path_url: "spotlight",
        path_mdx: "content-mdx/extensions/others/spotlight.mdx",
        description: "Rust UI component that displays a spotlight.",
        tags: &[],
    },
    DemoExtensions {
        name: "Hamburger Menu",
        path_url: "hamburger-menu",
        path_mdx: "content-mdx/extensions/others/hamburger-menu.mdx",
        description: "Rust UI component that displays a hamburger menu.",
        tags: &[],
    },
    DemoExtensions {
        name: "Card 3D Flip Rotation",
        path_url: "card-3d-flip-rotation",
        path_mdx: "content-mdx/extensions/others/card-3d-flip-rotation.mdx",
        description: "Rust UI component that displays a card 3d flip rotation.",
        tags: &[],
    },
    DemoExtensions {
        name: "Announcement",
        path_url: "announcement",
        path_mdx: "content-mdx/extensions/others/announcement.mdx",
        description: "Rust UI component that displays an announcement.",
        tags: &[],
    },
    DemoExtensions {
        name: "Loaders",
        path_url: "loaders",
        path_mdx: "content-mdx/extensions/others/loaders.mdx",
        description: "A collection of loaders, made with Tailwind CSS.",
        tags: &[],
    },
    DemoExtensions {
        name: "Slider Hover",
        path_url: "slider-hover",
        path_mdx: "content-mdx/extensions/others/slider-hover.mdx",
        description: "Rust UI component that displays a slider hover effect.",
        tags: &[],
    },
    DemoExtensions {
        name: "Animated Background",
        path_url: "animated-background",
        path_mdx: "content-mdx/extensions/others/animated-background.mdx",
        description: "Rust UI component that displays an animated background.",
        tags: &[],
    },
    DemoExtensions {
        name: "Carousel Parallax",
        path_url: "carousel-parallax",
        path_mdx: "content-mdx/extensions/others/carousel-parallax.mdx",
        description: "Rust UI component that displays a Carousel with a parallax effect.",
        tags: &["carousel", "parallax"],
    },
    DemoExtensions {
        name: "Text Slide",
        path_url: "text-slide",
        path_mdx: "content-mdx/extensions/others/text-slide.mdx",
        description: "Rust UI component that displays a text slide effect.",
        tags: &[],
    },
    DemoExtensions {
        name: "Orbiting Circles",
        path_url: "orbiting-circles",
        path_mdx: "content-mdx/extensions/others/orbiting-circles.mdx",
        description: "Rust UI component that displays a set of orbiting circles.",
        tags: &[],
    },
    DemoExtensions {
        name: "Parallax Simple",
        path_url: "parallax-simple",
        path_mdx: "content-mdx/extensions/others/parallax-simple.mdx",
        description: "Rust UI component that displays a simple parallax effect.",
        tags: &[],
    },
];