use crate::models::demo_shared::DemoExtensions;

// * This file was generated automatically with build_registry.

pub const SIDENAV_EXTENSIONS_CSS: &[DemoExtensions] = &[
    DemoExtensions {
        name: "Always Great Grid",
        path_url: "always-great-grid",
        path_mdx: "content-mdx/extensions/css/always-great-grid.mdx",
        description: "Rust UI component that displays CSS Always Great Grid.",
        tags: &["css"],
    },
    DemoExtensions {
        name: "Cursor Multi Color",
        path_url: "cursor-multi-color",
        path_mdx: "content-mdx/extensions/css/cursor-multi-color.mdx",
        description: "Rust UI component that displays CSS Cursor Multi Color.",
        tags: &["css"],
    },
    DemoExtensions {
        name: "Gallery Zoom",
        path_url: "gallery-zoom",
        path_mdx: "content-mdx/extensions/css/gallery-zoom.mdx",
        description: "Rust UI component that displays a collection of gallery zoom.",
        tags: &[],
    },
    DemoExtensions {
        name: "Triggered Highlight",
        path_url: "triggered-highlight",
        path_mdx: "content-mdx/extensions/css/triggered-highlight.mdx",
        description: "Rust UI component that displays CSS Triggered Highlight.",
        tags: &["css"],
    },
    DemoExtensions {
        name: "Carousel 3D Rotating",
        path_url: "carousel-3d-rotating",
        path_mdx: "content-mdx/extensions/css/carousel-3d-rotating.mdx",
        description: "Rust UI component that displays CSS Carousel 3D Rotating.",
        tags: &["css"],
    },
    DemoExtensions {
        name: "Cards Glowing",
        path_url: "cards-glowing",
        path_mdx: "content-mdx/extensions/css/cards-glowing.mdx",
        description: "Rust UI component that displays CSS Cards Glowing.",
        tags: &["css"],
    },
    DemoExtensions {
        name: "Sticky Cursor Links",
        path_url: "sticky-cursor-links",
        path_mdx: "content-mdx/extensions/css/sticky-cursor-links.mdx",
        description: "Rust UI component that displays a sticky cursor links.",
        tags: &[],
    },
    DemoExtensions {
        name: "Cards Follow Shadow",
        path_url: "cards-follow-shadow",
        path_mdx: "content-mdx/extensions/css/cards-follow-shadow.mdx",
        description: "Rust UI component that displays a collection of cards follow shadow.",
        tags: &[],
    },
    DemoExtensions {
        name: "Docker",
        path_url: "docker",
        path_mdx: "content-mdx/extensions/css/docker.mdx",
        description: "Rust UI component that displays CSS Docker.",
        tags: &["css"],
    },
    DemoExtensions {
        name: "Universe Rotating",
        path_url: "universe-rotating",
        path_mdx: "content-mdx/extensions/css/universe-rotating.mdx",
        description: "Rust UI component that displays CSS Universe Rotating.",
        tags: &["css"],
    },
    DemoExtensions {
        name: "Gallery Vercel",
        path_url: "gallery-vercel",
        path_mdx: "content-mdx/extensions/css/gallery-vercel.mdx",
        description: "Rust UI component that displays CSS Gallery Vercel.",
        tags: &["css"],
    },
    DemoExtensions {
        name: "Wheel Headings",
        path_url: "wheel-headings",
        path_mdx: "content-mdx/extensions/css/wheel-headings.mdx",
        description: "Rust UI component that displays CSS Wheel Headings.",
        tags: &["css"],
    },
    DemoExtensions {
        name: "Select Price Table",
        path_url: "select-price-table",
        path_mdx: "content-mdx/extensions/css/select-price-table.mdx",
        description: "Rust UI component that displays a select price table.",
        tags: &["css"],
    },
    DemoExtensions {
        name: "Card Focus",
        path_url: "card-focus",
        path_mdx: "content-mdx/extensions/css/card-focus.mdx",
        description: "Rust UI component that displays CSS Card Focus.",
        tags: &["css"],
    },
    DemoExtensions {
        name: "Radar Mini",
        path_url: "radar-mini",
        path_mdx: "content-mdx/extensions/css/radar-mini.mdx",
        description: "Rust UI component that displays a radar mini.",
        tags: &[],
    },
    DemoExtensions {
        name: "CSS Pills",
        path_url: "css-pills",
        path_mdx: "content-mdx/extensions/css/css-pills.mdx",
        description: "Rust UI component that displays CSS Pills.",
        tags: &["css"],
    },
    DemoExtensions {
        name: "Card Wobble",
        path_url: "card-wobble",
        path_mdx: "content-mdx/extensions/css/card-wobble.mdx",
        description: "Rust UI component that displays a card wobble.",
        tags: &[],
    },
    DemoExtensions {
        name: "Tabs Shadow",
        path_url: "tabs-shadow",
        path_mdx: "content-mdx/extensions/css/tabs-shadow.mdx",
        description: "Rust UI component that displays CSS Tabs Shadow.",
        tags: &["css"],
    },
    DemoExtensions {
        name: "Steps Indicator",
        path_url: "steps-indicator",
        path_mdx: "content-mdx/extensions/css/steps-indicator.mdx",
        description: "Rust UI component that displays a steps indicator.",
        tags: &["css"],
    },
    DemoExtensions {
        name: "Rain Letters",
        path_url: "rain-letters",
        path_mdx: "content-mdx/extensions/css/rain-letters.mdx",
        description: "Rust UI component that displays CSS Rain Letters.",
        tags: &["css"],
    },
];