macro_names = [ "leptos::view", "view"]

max_width = 100 
tab_spaces = 4 
indentation_style = "Auto" # "Tabs", "Spaces" or "Auto"
newline_style = "Auto" # "Unix", "Windows" or "Auto"
attr_value_brace_style = "WhenRequired" # "Always", "AlwaysUnlessLit", "WhenRequired" or "Preserve"
closing_tag_style = "Preserve" # "Preserve", "SelfClosing" or "NonSelfClosing"

[attr_values]
class = "Tailwind"
